### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by cmitch** [SuperElastix/SimpleElastix#204]
I am trying to install SimpleElastix/SimpleITK on an Ubuntu computer for either Python2 or 3, whichever we can get to work. Using pip install doesn't work as various methods don't import then (e.g. no "GetDefaultParameterMethod" exists). I tried following the instructions on their website (https://simpleelastix.readthedocs.io/GettingStarted.html#compiling-on-linux), but even though no errors are thrown throughout the process, I am still unable to import. For Python3, the typical "No module" error pops up, but for Python2 I get the following:

```
import SimpleITK as sitk 
Traceback (most recent call last): 
File "", line 1, in File "/usr/local/lib/python2.7/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py2.7-linux-x86_64.egg/SimpleITK/init.py", 
line 1, in from .SimpleITK import * File "/usr/local/lib/python2.7/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", 
line 17, in _SimpleITK = swig_import_helper() File "/usr/local/lib/python2.7/dist-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py2.7-linux-x86_64.egg/SimpleITK/SimpleITK.py", 
line 16, in swig_import_helper return importlib.import_module('_SimpleITK') File "/usr/lib/python2.7/importlib/init.py", 
line 37, in import_module import(name) 
ImportError: No module named _SimpleITK
```

Any help would be greatly appreciated :)

**Comment by samieti02** [comment]
Hello dear sir @kaspermarstal 
I didnt want to start a new issue, so i write it here.
I have a issue with the installation of the wheel data and it is really annoying. I saw on the internet page that there are 2 methods on how to install; either with the binary files or with the wheel data. Since I want to use it with python , I ran the command pip install whl_data. And the installation with pip was successful
But now when I want to use the very simple codeline for registration of the documentation, i get that error

`return_load(spec)`
`ImportError: DLL load failed: The specified module was not found`

. Could you plese help me to solve that error?

Thanks!

**Comment by kaspermarstal** [comment]
I don't know why you see this error. Perhaps If you are on Windows check that you compiled with the version of Visual Studio that matches you python version.

Sorry for the late reply.

**Comment by kaspermarstal** [comment]
Feel free to reopen if this is still an issue.
