### ISSUE TITLE
Having trouble at the final step of compiling SimpleElastix to use with Simple ITK 

### ISSUE THREAD

**Issue by gkuling** [SuperElastix/SimpleElastix#307]
Using Windows 10, and Python 3. Trying to compile SimpleElastix so that it can be used with SimpleITK. 

When I go into \SimpleITK-build\Wrapping\Python\Packaging\ and run 

python setup.py.in install 

in the command line I get: 

C:\Users\rotation\Anaconda3\Lib\site-packages\SimpleElastix\SimpleITK-build\Wrapping\Python\Packaging>python setup.py.in install
running install
running bdist_egg
running egg_info
creating SimpleITK.egg-info
writing SimpleITK.egg-info\PKG-INFO
writing dependency_links to SimpleITK.egg-info\dependency_links.txt
writing top-level names to SimpleITK.egg-info\top_level.txt
writing manifest file 'SimpleITK.egg-info\SOURCES.txt'
reading manifest file 'SimpleITK.egg-info\SOURCES.txt'
writing manifest file 'SimpleITK.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\SimpleITK
copying C:\Users\rotation\Anaconda3\Lib\site-packages\SimpleElastix\SimpleITK-build\Wrapping\Python\SimpleITK.py -> build\lib.win-amd64-3.6\SimpleITK
copying C:\Users\rotation\Anaconda3\Lib\site-packages\SimpleElastix\SimpleITK-build\Wrapping\Python\__init__.py -> build\lib.win-amd64-3.6\SimpleITK
running build_ext
error: can't copy 'C:\Users\rotation\Anaconda3\Lib\site-packages\SimpleElastix\SimpleITK-build\Wrapping\Python\Packaging\@SimpleITK_BINARY_MODULE@': doesn't exist or not a regular file

Not sure why it's trying to copy a folder?

**Comment by kaspermarstal** [comment]
You need to run the "setup.py" file, not the "setup.py.in" file.

**Comment by gkuling** [comment]
Hello @kaspermarstal 

So I redownloaded and built the package again with cmake and visual studio, and the setup.py file doesn't get built. 

Any idea why this may be happening?

**Comment by h-armin** [comment]
Hi guys!
I actually get the same error on Ubuntu 18.04 LTS. And I also get a setup.py.in instead of an setup.py file (but apart from that, I think it may be the same file).

So you believe me:
`~/build/SimpleITK-build/Wrapping/Python/Packaging$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing SimpleITK.egg-info/PKG-INFO
writing top-level names to SimpleITK.egg-info/top_level.txt
writing dependency_links to SimpleITK.egg-info/dependency_links.txt
reading manifest file 'SimpleITK.egg-info/SOURCES.txt'
writing manifest file 'SimpleITK.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
error: can't copy '/home/johannes/build/SimpleITK-build/Wrapping/Python/Packaging/@SimpleITK_BINARY_MODULE@': doesn't exist or not a regular file
`

Does a more experienced Linux user know more about this?

**Comment by gkuling** [comment]
So I found a solution to my issue. 
I am not well experienced in using cmake and visual studio, therefore I was making elementary mistakes. 

1. It is crucial to choose the proper visual studio (VS) compiler installed on your computer when using cmake. 
- On the getting started site (https://simpleelastix.readthedocs.io/GettingStarted.html) this is step 2. 

2. Do not run the command 'msbuild ALL_BUILD.vcxproj /p:Configuration=Release' from command prompt if your VS compiler is notsetup in your environment vairables. 
- Best to follow the site documentation in step 3 and use the 'VS20** x64 Native Tools Command Prompt' corresponding to your installed VS. 

Sorry kaspermarstal for not reading your directions fully.
