### ISSUE TITLE
Fixed image coordinate system not mapping to Moving image coordinate system using Transformix

### ISSUE THREAD

**Issue by ctorti** [SuperElastix/SimpleElastix#386]
Hello all,

I have two series of DICOM images that I call FixedIm and MovingIm.  I register MovingIm to FixedIm as follows:

`ElastixImFilt = sitk.ElastixImageFilter()`

`ElastixImFilt.SetFixedImage(FixedIm)`
`ElastixImFilt.SetMovingImage(MovingIm)`
    
`ElastixParamMap = sitk.GetDefaultParameterMap('affine')`
    
`ElastixParamMap['AutomaticTransformInitialization'] = ['true']`
`ElastixParamMap['AutomaticTransformInitializationMethod'] = ['GeometricalCenter']`
`ElastixParamMap['WriteIterationInfo'] = ['true']`
`ElastixParamMap['MaximumNumberOfIterations'] = ['512']`
`ElastixParamMap['UseDirectionCosines'] = ['true']`

`ElastixImFilt.SetParameterMap(ElastixParamMap)`

`ElastixImFilt.Execute()`

`RegIm = ElastixImFilt.GetResultImage()`

The registration result looks reasonable but I run into problems further ahead with points that I transform using Transformix:

Say that 'FixedPoints' are contour points from a ROI in the Fixed image domain.  I create an inputpoints.txt file as specified in the Elastix manual and transform them as follows:

`TransformixImFilt = sitk.TransformixImageFilter()`

`TransformixImFilt.SetTransformParameterMap(TransformFilter.GetTransformParameterMap())`

`TransformixImFilt.SetFixedPointSetFileName('inputpoints.txt')`
    
`TransformixImFilt.SetMovingImage(MovingIm)`
    
`TransformixImFilt.Execute()`

With the aim of checking my work, I used the following simple test case:  I generated a list of points that lie in each imaging plane in the Fixed image domain:

`FixedPoints = [ [point0_0, point1_0, point2_0, point3_0, point0_0],`
`                         [point0_1, point1_1, point2_1, point3_1, point0_1],`
`                         ...`
`                       ]`

where each list consists of the 4 points that mark out the 4 corners of the image plane + the 1st point repeated to close the "contour" for each image plane in FixedIm.

The points are defined using the image attributes: The origin, direction cosines and pixel spacings.

If I plot FixedPoints and the Fixed image planes I get what I expect:

![Fig1_Points_on_Fixed_image_planes_and_Fixed_image_planes](https://user-images.githubusercontent.com/26715524/90015139-185f5380-dca0-11ea-9681-98866ff68953.png)

Yet plotting the transformed points and the Moving image planes the points do not coincide with the planes:

![Fig2_Transformed_points_on_Fixed_image_planes_and_Moving_image_planes](https://user-images.githubusercontent.com/26715524/90015571-afc4a680-dca0-11ea-8358-b94e6a513654.png)

Interestingly, the transformed points seem to be parallel to the Fixed image planes but displaced along the scan direction:

![Fig4_Transformed_points_on_Fixed_image_planes_and_Fixed_image_planes](https://user-images.githubusercontent.com/26715524/90016552-126a7200-dca2-11ea-8d96-bf7cb65eba82.png)

Since the direction cosines of FixedIm and MovingIm are different I don't expect the planes created from the transformed points to be parallel to the Fixed imaging planes.

But more importantly my question is this - should I not expect the points that lie on the Fixed image planes to transform to points that lie on the Moving image planes?

Afterall I set:

`ElastixParamMap['UseDirectionCosines'] = ['true']`

so presummably the Fixed coordinate system should map directly to the Moving coordinate system upon applying Transformix?

Any clarity on this would be much appreciated.

**Comment by sorenchr2011** [comment]
Hi,
 I don't think you can expect that the transformed fixed points lie on the
moving image planes - only under certain circumstances would that happen.
The transformed points indicate where samples should be taken in the moving
image in order to match the fixed image. For example a point A in the fixed
image may fall within 2 adjacent slices in B - so that is not on any moving
plane for example. Another example: say that the moving and fixed grid are
identical, if the object is rotated 45 degrees between the two grids, the
transformed fixed point grid will then be 45 degrees off compared to the
moving grid. I think the only thing you should expect to see in your
experiment is some degree of overlap between transformed fixed and moving
for a successful registration - as you do. (overlap does not rule out a bad
reg though).
In case you are doing this to verify that you correctly map your contour
from voxel space to world, then you could consider transforming the voxel
coordinates directly for simplicity - less work. I believe transformix has
an option for that. Youd could round the transformed points to nearest
coord and create a transformed ROI in moving space, keeping in mind that it
is rounded to nearest voxel of course.

Soren

**Comment by ctorti** [comment]
Hi Soren,

Thanks very much for your helpful response.  I've been flip-flopping over this question for a while now and it's useful to get confirmation that the planes don't necessarily map from one domain to another.

As for your other comment, I will return to this ASAP but I wanted to avoid further delaying my message of thanks.

Till then,
Cristiano
